Feature/close pr
xalvarez/prevent-file-change-action pull request #1065
Opened 2024-12-19 20:46 UTC by HasanHajHasan

Adding close PR feature as an option instead of failing it

2024-12-19 22:22 UTC, xalvarez requested changes
Hello @HasanHajHasan,

Thank you for your contribution!

I added some comments to your PR. It would be great if you could address them. If you need help with the adjustments, let me know and I can take over.

2024-12-19 22:22 UTC, xalvarez commented on src/main.ts
> +      const githubService = new GithubService(githubToken)
Would you mind not renaming this variable?

2024-12-19 22:22 UTC, xalvarez commented on src/pattern-matcher.ts
> +        })
There's a GitHubService class which is responsible for interacting with GitHub. Adding this call here mixes responsibilities. I think a cleaner code would be:

```
if (closePR) {
        await githubService.closePullRequest(owner, repo, pullRequestNumber)
      } else {
        core.setFailed(`There is at least one file matching the pattern ${pattern}`)
      }
```

Additionally, the tests for this API call are missing, which is way the PR check is failing (coverage threshold isn't reached).

2024-12-19 22:22 UTC, xalvarez commented on src/pattern-matcher.ts
> +      const closePR: boolean = core.getInput('closePR') === 'true'
All inputs are read in main.ts. For consistency I would read this there too.

2024-12-26 12:23 UTC, HasanHajHasan commented
Hey @xalvarez,
Is there any missing or incomplete step|(s) needed to be done ? so we can proceed with the merge

2024-12-26 13:15 UTC, HasanHajHasan commented
Hey @xalvarez,
Is there any missing or incomplete step|(s) needed to be done ? so we can proceed with the merge

2024-12-26 13:25 UTC, xalvarez commented
Hi @HasanHajHasan, thanks for your changes! I'm currently on vacation and I can't properly review these changes right now. I'll take care of this PR as soon as I can.

2024-12-29 21:48 UTC, xalvarez approved these changes
Thanks for your contribution @HasanHajHasan! I'll merge these changes and prepare a release.

2024-12-29 21:49 UTC, merged